.env.sample, .gitignore, requirements.txt, requirements_dev.txt, rh/templates/rh/projects/forms/project_form.html, rh/templates/rh/projects/views/projects_view_base.html, rh/tests.py, rh/tests/test_urls.py, rh/tests/test_views.py, rh/urls.py, scripts/migrate_mongodb.py
- Packages updated in dev_requirements and requirements file.
- Some HTML fixes
- Script changes
- Started Test cases for rh urls, views, and models.
=> Rh test cases

scripts/sonatype.sh
Feature: added sonatype to check vulnerabilities in dependencies
=> Add sonatype to check packages vulnerabilities

scripts/owasp_zap.sh
Feature: added owasp zap as a bash script shell for security purpose. 
Regression & impact: no impact.
=> Add owasp_zap script to run security checks in django

.vscode/launch.json, src/rh/models.py, src/rh/templates/rh/projects/forms/activity_empty_form.html, src/rh/templates/rh/projects/forms/project_activity_plan_form.html, src/static/rh/js/activity_planning.js
=> [FIX] - Minor fixes

.github/workflows/main.yml
Done: Continuous Deployment to Dev server
=> Continuous Deployment to Dev server

src/rh/exports.py, src/rh/templates/rh/projects/views/project_view.html, src/rh/urls.py, src/rh/views.py, src/static/src/js/utils/exportSW.js
=> project fields filter and export created

src/core/settings/base.py, src/rh/templates/rh/projects/forms/organization_register_form.html, src/rh/templates/rh/projects/forms/project_activity_plan_form.html, src/rh/templates/rh/projects/forms/project_form.html, src/rh/urls.py, src/static/rh/js/all_projects.js, src/static/src/styles/layout/_common.scss, src/stock/templates/stock/stock_report_form.html, src/templates/_base.html, src/users/templates/users/registration/login.html, src/users/templates/users/registration/signup.html
alert messages display designed and positioned nicely
=> message alert display fixed and designed

poetry.lock, pyproject.toml, src/core/settings/local.py, src/project_reports/views.py, src/rh/factory.py, src/rh/forms.py, src/rh/urls.py, src/rh/views.py, src/static/project_reports/js/monthly_report_progress.js, src/static/rh/js/activity_planning.js, src/static/rh/js/project_planning.js, src/static/src/js/utils/export.js
Useful tool: `poetry run python src/manage.py tui`
=> Optimizes queries and added dev tool django-tui

src/static/src/styles/layout/_common.scss, src/users/static/users/users.js, src/users/templates/users/registration/login.html
showing the user password and hide it while logging to the platform
=> toggle between show and hide password

src/static/src/styles/layout/_common.scss
=> filter fixed

src/rh/templates/rh/projects/views/projects_list.html, src/static/src/styles/layout/_common.scss, src/stock/templates/stock/all_stock_report.html, src/stock/templates/stock/stocks_index.html, src/users/forms.py, src/users/templates/users/profile.html, src/users/views.py
Some User Experiences issues fixed
=> Minor user experience fixes #1

src/static/src/styles/layout/_common.scss, src/stock/templates/stock/stock_report_form.html, src/stock/templates/stock/stock_report_view.html, src/stock/urls.py, src/stock/views.py, src/templates/_base.html
Features:
1. Drop-down added for adding Warehouse and Stock report 
2. Edit Submitted stock designed 
3. Edit Submitted Stock implemented
=> Minor user experience fixes #2

src/rh/templates/rh/projects/forms/project_form.html, src/users/forms.py
Changes:
User are not able to change their organization and country 
Implementing partner and program partner change field change
=> Minor user experience fixes #3

src/rh/exports.py, src/rh/resources.py
resource file fixed and working...
=> Export fixes resource

src/rh/resources.py, src/rh/views.py
dis-aggregation field in excel file fixed
=> Export Resource file fixed

src/core/settings/local.py, src/rh/exports.py, src/rh/models.py, src/rh/resources.py, src/rh/templates/rh/projects/forms/target_location_empty_form.html, src/rh/templates/rh/projects/views/project_view.html, src/rh/views.py, src/static/src/js/utils/exportSW.js
Export filter missing field added and completed
=> Project select export

src/rh/exports.py, src/rh/resources.py, src/rh/templates/rh/projects/views/project_view.html, src/rh/urls.py, src/rh/views.py, src/static/src/js/utils/exportSW.js, src/static/src/styles/layout/_common.scss
project export in csv format created and some additional feature of counting the number of selected field added.
=> Create export csv

src/rh/models.py, src/rh/templates/rh/projects/views/project_view.html, src/rh/views.py, src/users/forms.py, src/users/templates/users/registration/login.html
The eye icon for show-hide password fixed 
checkbox for selecting province fixed
=> checkboxes and eye for passwor show-hide fixed

src/rh/templates/rh/projects/views/project_view.html
check boxes for filter and export fixed
=> the checkbox grouping fixed

src/rh/forms.py, src/rh/models.py, src/rh/resources.py, src/rh/templates/rh/projects/forms/project_form.html, src/rh/templates/rh/projects/forms/target_location_empty_form.html, src/rh/templates/rh/projects/views/_projects_details.html, src/rh/templates/rh/projects/views/projects_list.html, src/rh/views.py, src/static/src/js/utils/exportSW.js, src/static/src/styles/layout/_common.scss, src/stock/models.py, src/stock/views.py
1. required asterisk added to facility site name and facility site ID
2. caption [HMIS code] added to facility site ID
3. start date cannot be greater than end date  validation added to project form
4. bulk export customized according to user project selection
5. the export file renamed in Bulk Export
6. province and district sorted from A-Z
=> Health fixes

src/core/settings/base.py, src/rh/management/commands/load_activities.py, src/rh/templates/rh/projects/forms/project_form.html, src/static/src/styles/layout/_common.scss
hints added for describing the project implement and program partners
=> Implement programme info

src/project_reports/forms.py, src/project_reports/templates/project_reports/forms/monthly_report_form.html
selecting the start and end date of monthly report fixed but, end date limitation is not implemented.
=> Date picker fixed

src/core/settings/base.py, src/rh/resources.py, src/static/src/js/utils/exportSW.js
Exporting list of project fixed
bugs in exportSW.js file removed
=> Export project list

src/rh/templates/rh/projects/views/projects_list.html, src/static/src/js/utils/exportSW.js, src/static/src/styles/layout/_common.scss
filtering project data listed
bugs removed from javascript exportSw.js file
=> Filter applied data

src/static/src/js/utils/exportSW.js
filter currency error fixed in export
=> filter fixed in export

src/rh/templates/rh/projects/views/projects_list.html, src/static/src/js/utils/exportSW.js, src/static/src/styles/vendors/choices.css
spinner added for bulk export button
=> spinner added to bulk export button

src/project_reports/forms.py, src/rh/forms.py
=> Revert "disaggregation names list disabled to change by the user"

src/rh/templates/rh/projects/views/projects_list.html, src/static/src/styles/layout/_common.scss
filter icon added to the project filter items
=> fiter item customized and added on the top of the page

src/rh/templates/rh/projects/views/_projects_pager.html, src/rh/views/projects.py, src/templates/components/header.html, src/users/models.py, src/users/templates/users/users_list.html, src/users/urls.py, src/users/views.py
=> fixes long pagination links

src/rh/forms.py, src/rh/views/target_locations.py
Target Location set to display according logged in user location
=> targetlocaion displays according to user location

src/rh/forms.py, src/rh/views/activity_plans.py
missing information added to target location update/edit projects
=> targetlocaion bugs removed from editing the project activity plan

src/rh/templates/rh/projects/views/project_view.html, src/rh/urls.py, src/rh/views/exports.py, src/static/src/js/utils/exportSW.js, src/static/src/styles/vendors/choices.css
filter and export customized and and file type added
bugs removed form exporting
=> filter and export customized and fixed

src/guides/views.py
user guide ordered according to its entry
=> ordering added to user guide content

.github/workflows/quality_assurance.yml, Makefile
=> Revert "fix settings in QA"

.github/workflows/quality_assurance.yml
=> Revert "no dev pip packages in QA"

src/project_reports/templates/project_reports/report_activity_plans/import_report_activity_plans.html, src/project_reports/views/monthly_reports.py, src/project_reports/views/views.py
1. Import report fixed
2. download from the last month mapped according to template file for importing the report
3. necessary guidance added to import the downloaded last month activities
=> Import report changes

src/project_reports/exports.py, src/project_reports/templates/project_reports/dashboards/reports_dashboard.html, src/project_reports/templates/project_reports/monthly_reports/views/_reports_table.html, src/project_reports/utils.py, src/rh/templates/rh/projects/views/_project_export_drawer.html, src/static/js/utils/exportSW.js, src/static/styles/components/_actions-panel.scss, src/static/styles/layout/_common.scss
small changes made for fixing the issues
=> small changes applied

src/project_reports/utils.py
=> monthly report fixed

src/project_reports/exports.py
=> small changes made on export

src/project_reports/dashboards.py, src/project_reports/utils.py, src/static/styles/components/_actions-panel.scss, src/users/views/auth.py
filter button fixed.
export monthly report fixed
cluster dashboard fixed
=> Login logout flash message

src/rh/templates/rh/projects/views/_projects_table.html, src/rh/views/exports.py, src/static/styles/layout/_common.scss, src/users/templates/users/partials/_users_table.html, src/users/urls.py, src/users/utils.py, src/users/views/users.py
export organization members added to organization->members page
=> Export organization members developed

src/rh/views/exports.py
location classification added to the export file 
location type removed from export file
=> classification added to the project export file

src/project_reports/forms.py, src/project_reports/templates/project_reports/monthly_reports/forms/monthly_report_form.html, src/project_reports/templates/project_reports/monthly_reports/views/_reports_table.html, src/project_reports/templates/project_reports/monthly_reports/views/monthly_report_view.html, src/project_reports/views/monthly_reports.py, src/rh/views/projects.py, src/static/styles/layout/_common.scss
monthly progress archive report fixed
update monthly report fixed
=> Project report fixes

src/project_reports/templates/project_reports/org_5w_dashboard.html, src/project_reports/templates/project_reports/report_activity_plans/import_report_activity_plans.html, src/project_reports/utils.py, src/project_reports/views/monthly_reports.py, src/project_reports/views/views.py
5w dashboard graph styled
import report template customized and necessary data such as Project Indicator,activity domain, activity types and location details added to the template as dropdown list for better efficiancy
=> Bring minor changes

src/project_reports/templates/project_reports/monthly_reports/views/monthly_reports_view_base.html, src/rh/views/projects.py
user not allowed to add report to a completed project.
user not allowed to complete a project if it has pending reports
=> Completing project fixes

src/users/forms.py, src/users/templates/users/auth/signup.html
=> remove the disable password radio field and add helper text in the reg

src/project_reports/templates/project_reports/cluster_5w_dashboard.html, src/project_reports/templates/project_reports/org_5w_dashboard.html, src/project_reports/views/dashboards.py, src/stock/forms.py, src/stock/views.py
stock report fixed
total beneficiary by disaggregation added to cluster and organization 5w
=> Fixing rh branch

src/project_reports/exports.py, src/project_reports/views/dashboards.py, src/rh/templates/rh/projects/views/project_view.html
=> Include only Activity Domain of selected cluster in multi cluster

src/stock/templates/stock/_stock_table_list.html, src/stock/templates/stock/stock_report_form.html
option added for selecting project for stock report
=> Customize stock report

src/project_reports/views/monthly_reports.py, src/templates/components/footer.html, src/users/views/users.py
download last month report fixed
user Guide link in the footer updated to the dynamic user guide
=> download last month report bug fixed

src/project_reports/views/monthly_reports.py, src/users/templates/users/emails/notification_email_template.html, src/users/views/auth.py, src/users/views/users.py
create account notification email created
copy monthly report fixed
organization memeber's filter fixed
=> email template for new user registration created

src/stock/templates/stock/_report_period_table.html, src/stock/templates/stock/_stock_table_list.html, src/stock/templates/stock/create_warehouse_location_form.html, src/stock/templates/stock/stock_report_form.html, src/stock/views.py
delete warehouse and delete stock report fixed
=> stock report along with warehous fixed

src/rh/templates/rh/financial_reports/_budget_progress_table.html, src/rh/views/budget_progress.py
financial report calculation added.
front-end fixed
=> financial report calculation added and front-end fixed

src/project_reports/templates/project_reports/monthly_reports/views/_reports_table.html, src/project_reports/utils.py
export report 5w fixed
beneficiary status and implementing partner dropdown added
=> export 5w and import template fixed

src/core/wsgi.py
=> Revert "revert wsgi changes" - environ in wsgi

src/rh/templates/rh/target_locations/target_location_form.html, src/rh/views/target_locations.py
Facility Monitoring disabled for FSAC in Project/activity Planning/add target location and update target location
=> Facility Monitoring disabled for FSAC Cluster
